name: message_bus
description: message bus library
version: 1.0.0
author: bob
homepage: http://bsteele.com/index.html

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen:

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0